### ISSUE TITLE
Entry points can be incorrectly omitted from origins in assets file

### ISSUE THREAD

**Issue by tomkelsey** [themgoncalves/react-loadable-ssr-addon#8] opened 2018-11-27 15:38 UTC
## Expected Behavior
For the entries in "entrypoints" in the asset manifest to also be keys in "origins"

## Current Behavior
I have a situation where the above isn't happening.

I think what is happening is that:

- I use react-loadable for a small component.
- I think webpack is seeing enough overlap between my entrypoint and the small component to combine them into one chunk.
- Then when `getChunkOrigin` runs, it finds the import statement for my small component (which is also the entrypoint chunk) and adds an entry into "origins" under `/Components/SmallComponent`
- `origins.size` is not 0 and therefore `names[0]` (the name of the entrypoint) is never added as an origin key.
- This then causes the entrypoint bundles not to be loaded

## Possible Solution
Potentially adding something like this to the end of `getChunkOrigin`:

```
    if (this.entrypoints.has(names[0])) {
      origins.add(names[0]);
    }
```

I'm working with a very rudimentary understanding of how things work so I don't know if this is the right approach and, if so, whether we also need to check the other entries in `names` or against the `id` too.

**Comment by themgoncalves** [comment] 2018-11-30 10:51
Hi @tomkelsey,

Thanks for reporting, I'll investigate this issue and after that, will post the outcome.

Cheers,

**Comment by KevinGruber** [comment] 2019-02-01 16:04
@themgoncalves 

i have the same problem did you fin time already to investigate into that problem?

BR,
Kev

**Comment by themgoncalves** [comment] 2019-02-05 15:42
@KevinGruber sorry guys, sadly this issue still on _investigation_, my time has been pretty hectic lately.

I'll try to close it as soon as possible, thanks for the understanding.

Cheers,

**Comment by themgoncalves** [comment] 2019-02-08 10:30
@tomkelsey or @KevinGruber  is it possible for you to share a small implementation with this issue? I'm having trouble to reproduce it and therefore, to potentially fix it.

**Comment by themgoncalves** [comment] 2019-02-08 11:02
If I understood this issue correctly, you guys are placing `react-loadable` as application entrypoint in the `ReactDOM.hydrate(<AppAsync />, document.getElementById('app'));`, is that right?

Example:

```jsx harmony
import React from 'react';
import ReactDOM from 'react-dom';
import Loadable from 'react-loadable';
import Loading from './components/Loading';

const AppExample = Loadable({
  loader: () => import(/* webpackChunkName: "app" */'./components/App'),
  loading: Loading,
});

window.onload = () => {
  Loadable.preloadReady().then(() => {
    ReactDOM.hydrate(<AppExample />, document.getElementById('app'));
  });
};
```

If so, the chunk `app.chunk.js` are indeed not being _output_ in the html, but it seems to be an **issue with `react-loadable`**.

if you `console.log(Array.from(modules))` in the `server.js`, you will see that **it is not requested** the `./components/App`, therefore, `react-loadable-ssr-addon` has no means to know what should be retrieved.

So this is what we get from the example available in the project:

```js
// console.log(Array.from(modules))
[ './Header',
  './Content',
  './ContentNested',
  './multilevel/Multilevel',
  './SharedMultilevel',
  './level-1/level-2/DeepLevel',
  '../../SharedMultilevel' ]
```

**Comment by KevinGruber** [comment] 2019-02-08 11:10
Hi @themgoncalves,

Sadly not. :-( 
but i am using react-router config and i am doing a renderRoutes(Routes)
Routes has a fixed App Component which is not lazyloaded and thatn lazyloaded Sub Pages.
So from my understanding it should be still there...

But maybe i am misunderstanding it.

BR,
Kevin

**Comment by themgoncalves** [comment] 2019-02-08 11:18
@KevinGruber I see, but I totally can not reproduce the `issue` reported here. 

Also, to keep in mind that `entrypoints` **is every file defined in `webpack entrypoints`**, so it should be in the `react-loadable-ssr-addon.json` file under the `entrypoints array`, otherwise, it should not.

**Comment by themgoncalves** [comment] 2019-02-12 10:13
I'll close this issue due to lack of data to investigate.

**Closed as completed by themgoncalves** 2019-02-12 10:13 UTC
Labels: investigation
